AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Rainer Portfolio Backend - Local API'

Globals:
  Function:
    Timeout: 29
    MemorySize: 512
    Runtime: nodejs20.x
    Environment:
      Variables:
        NODE_ENV: dev
        DYNAMODB_TABLE_PREFIX: rainer-portfolio-backend-dev

Resources:
  BlogApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: rainer-portfolio-backend-api-dev
      CodeUri: src/lambda
      Handler: handler.lambdaHandler
      Runtime: nodejs20.x
      Environment:
        Variables:
          CORS_ORIGIN: '*'
          PORT: '4000'
          HOST: '0.0.0.0'
    Events:
      Api:
        Type: Api
        Properties:
          Path: /{proxy+}
          Method: ANY
