AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda
      Handler: handler.lambdaHandler
      Runtime: nodejs20.x
    Events:
      HelloWorld:
        Type: Api
        Properties:
          Path: /hello
          Method: get
