AWSTemplateFormatVersion: \ 2010-09-09\
Transform: AWS::Serverless-2016-10-31
Description: \Rainer Portfolio Backend - Simple Lambda\
Globals:
  Function:
    Timeout: 29
    MemorySize: 512
    Runtime: nodejs20.x
    Environment:
      Variables:
        NODE_ENV: dev
        DATABASE_PROVIDER: DYNAMODB
        DYNAMODB_ENDPOINT: http://localhost:8000
        CORS_ORIGIN: http://localhost:3000
        LOG_LEVEL: debug
Resources:
  BlogApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: rainer-portfolio-api-dev
      Handler: src/lambda/mock-handler.handler
      CodeUri: BlogApiFunction
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
    Metadata:
      SamResourceId: BlogApiFunction
