AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Rainer Portfolio Backend - NestJS Serverless on AWS Lambda
  DynamoDB + Cognito + Function URLs

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        NODE_ENV: !Ref Environment
        DYNAMODB_TABLE: !Ref DynamoDBTable
        COGNITO_USER_POOL_ID: !Ref CognitoUserPool
        COGNITO_CLIENT_ID: !Ref CognitoUserPoolClient
        AWS_REGION: !Ref AWS::Region
    Tracing: Active

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - staging
      - development
  StageName:
    Type: String
    Default: prod

Resources:
  # ============================================
  # DynamoDB Table - Single Table Design
  # ============================================
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${Environment}-portfolio-backend-table'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
        - AttributeName: GSI2PK
          AttributeType: S
        - AttributeName: GSI2SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI2
          KeySchema:
            - AttributeName: GSI2PK
              KeyType: HASH
            - AttributeName: GSI2SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: portfolio-backend

  # ============================================
  # Cognito User Pool
  # ============================================
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub '${Environment}-portfolio-users'
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: true
        - Name: name
          AttributeDataType: String
          Required: false
          Mutable: true
        - Name: nickname
          AttributeDataType: String
          Required: false
          Mutable: true
      LambdaConfig:
        PreSignUp: !GetAtt CognitoPreSignUpTrigger.Arn
      UserPoolTags:
        Environment: !Ref Environment
        Project: portfolio-backend

  # ============================================
  # Cognito User Pool Client
  # ============================================
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ClientName: !Sub '${Environment}-portfolio-web-client'
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days
      AccessTokenValidity: 1
      IdTokenValidity: 1
      RefreshTokenValidity: 30
      PreventUserExistenceErrors: ENABLED

  # ============================================
  # Lambda Functions
  # ============================================
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Environment}-portfolio-api'
      CodeUri: .
      Handler: dist/bootstrap/lambda.handler
      Architectures:
        - x86_64
      Layers:
        - !Ref NestJSLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTable
        - Statement:
            Effect: Allow
            Action:
              - cognito-idp:AdminInitiateAuth
              - cognito-idp:AdminRespondToAuthChallenge
              - cognito-idp:AdminSetUserPassword
              - cognito-idp:AdminUpdateUserAttributes
              - cognito-idp:AdminGetUser
              - cognito-idp:ListUsers
              - cognito-idp:AdminCreateUser
              - cognito-idp:AdminDeleteUser
            Resource: !GetAtt CognitoUserPool.Arn
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: RESPONSE_STREAM
        Cors:
          AllowOrigins:
            - '*'
          AllowMethods:
            - '*'
          AllowHeaders:
            - '*'
      Tags:
        Environment: !Ref Environment
        Project: portfolio-backend

  # ============================================
  # Lambda Layer - NestJS Dependencies
  # ============================================
  NestJSLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub '${Environment}-nestjs-dependencies'
      Description: Dependencies for NestJS application
      ContentUri: layers/njs.zip
      CompatibleRuntimes:
        - nodejs20.x
      LicenseInfo: MIT

  # ============================================
  # Cognito Triggers
  # ============================================
  CognitoPreSignUpTrigger:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Environment}-cognito-pre-signup'
      CodeUri: src/lambda
      Handler: cognito-pre-signup-trigger.handler
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - dynamodb:PutItem
              - dynamodb:UpdateItem
            Resource: 
              - !GetAtt DynamoDBTable.Arn
              - !Sub '${DynamoDBTable.Arn}/index/*'
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref DynamoDBTable
      Tags:
        Environment: !Ref Environment
        Project: portfolio-backend

  # ============================================
  # IAM Role for API Function
  # ============================================
  ApiFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${Environment}-portfolio-api-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:BatchGetItem
                  - dynamodb:BatchWriteItem
                Resource:
                  - !GetAtt DynamoDBTable.Arn
                  - !Sub '${DynamoDBTable.Arn}/index/*'
        - PolicyName: CognitoAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cognito-idp:AdminInitiateAuth
                  - cognito-idp:AdminRespondToAuthChallenge
                  - cognito-idp:AdminSetUserPassword
                  - cognito-idp:AdminUpdateUserAttributes
                  - cognito-idp:AdminGetUser
                  - cognito-idp:ListUsers
                  - cognito-idp:AdminCreateUser
                  - cognito-idp:AdminDeleteUser
                  - cognito-idp:SignUp
                  - cognito-idp:ConfirmSignUp
                  - cognito-idp:ForgotPassword
                  - cognito-idp:ConfirmForgotPassword
                Resource: !GetAtt CognitoUserPool.Arn

  # ============================================
  # Outputs
  # ============================================
Outputs:
  ApiFunctionUrl:
    Description: API Gateway Function URL
    Value: !GetAtt ApiFunction.FunctionUrl
  DynamoDBTableName:
    Description: DynamoDB table name
    Value: !Ref DynamoDBTable
  CognitoUserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref CognitoUserPool
  CognitoClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref CognitoUserPoolClient
  ApiFunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt ApiFunction.Arn
